#cloud-config

##############################################
###     EXAMPLE BIG-IP CLOUD-CONFIG        ###
##############################################
# Description:
# deploy a Standalone 1nic BIG-IP w/:
#   * iApp 
#     * HTTPS Virtual 
#     * ClientSSL profile using custom cert/key
#     * w/ WAF
# MGMT GUI Port will be on 8443

write_files:

  - path: /config/cloud/onboard.sh
    permissions: 0755
    owner: root:root
    content: |
      #!/bin/bash

      # Load Input Parameters
      . /config/cloud/onboard_config_vars

      # Download Onboarding Libs. 
      # Could be pre-packaged or hosted internally
      curl -o /config/cloud/f5-cloud-libs.tar.gz --silent --fail --retry 20 -L https://api.github.com/repos/F5Networks/f5-cloud-libs/tarball/develop
      tar xvzf /config/cloud/f5-cloud-libs.tar.gz -C /config/cloud/
      mv /config/cloud/F5Networks-f5-cloud-libs-* /config/cloud/f5-cloud-libs
      cd /config/cloud/f5-cloud-libs
      npm install --production

      # License / Provision
      f5-rest-node /config/cloud/f5-cloud-libs/scripts/onboard.js \
      -o  /var/log/onboard.log \
      --no-reboot \
      --host localhost \
      --user admin \
      --password ${BIGIP_ADMIN_PASSWORD} \
      --update-user "user:${BIGIP_ADMIN_USERNAME},password:${BIGIP_ADMIN_PASSWORD},role:admin,shell:tmsh" \
      --hostname ${HOSTNAME} \
      --global-setting hostname:${HOSTNAME} \
      --ssl-port 8443
      --ntp 0.us.pool.ntp.org \
      --ntp 1.us.pool.ntp.org \
      --tz UTC \
      --dns 8.8.8.8 \
      --module ltm:nominal \
      --module ltm:asm \
      --license ${BIGIP_LICENSE_KEY} \
      --ping www.f5.com 30 15 \

      # OPENSTACK NOTES: these images still have default admin/root accounts 
      # optional temp workaround for "-update-user"
      tmsh modify auth user admin shell tmsh

      ##### BEGIN NETWORK ########
      # Mostly Autoconfigured via DHCP

      # RUN USER CUSTOM COMMANDS
      f5-rest-node /config/cloud/f5-cloud-libs/scripts/runScript.js \
      --file /config/cloud/custom-config.sh \
      --cwd /config/cloud \ 
      -o /var/log/custom-config.log \


############ BEGIN USER CUSTOMIZE SECTION IN WRITE_FILES: ############

  - path: /config/cloud/onboard_config_vars
    permissions: 0755
    owner: root:root
    content: |
      #!/bin/bash

      HOSTNAME=demo.example.com

      BIGIP_ADMIN_USERNAME=admin
      BIGIP_ADMIN_PASSWORD=yourpassword
      BIGIP_ROOT_PASSWORD=yourpassword

      APP_NAME=demoService1
      VS_PORT=443
      POOL_DNS=www.f5.com
      POOL_MEMBER_PORT=80

      BIGIP_LICENSE_KEY=ZBVNS-ZSZRE-ISOTV-TSQIF-RYAOUQH

  # keys/certificates/etc.

  - path: /config/ssl/ssl.crt/website.crt
    encoding: gzip+base64
    content: H4sIAAWfZFgAA2VUy66jOBDd8xWzj1oXCHktemEb4zi5hphn8C44uYSEQCAJr69vcrs1Gk1bKsk6VS4fnTqqHz/GAzGh9j8Iuz61KAI+foM/FEapefMRAiVJQUshSMfwgQ3Ta3W+ZmTVqhDwwAImJIw/WsRjM+Sc4HYTBgP+VBi4EqAFGEGGQhV32AQOTO0QAulDzc7jvasmJOiICaLfOPNNPX8dSdgnUXhVDpGlCk+7xD44Wa3a2RcwMBP3Y+jsYh9GrGc+UJl5/RdjOO7QADbvhgoE49M89P9Dj4709tzHnAHjmx3s2DrQw/Nx7T6Ej2MG428cdHynbLPZzY5CI460dqT6ivXVc9QF0sv/dcAWAA4CfAneeZRuxzsGirbtpuZQmOmOGwMAVkF9oePz8JWFSHjoNXtZvZPMz9VCpXRq+NkHxlRcJ2ihz6tnVithtcy1QQ8l9gQnCYeVIci5jp1Fef88HzIOjTzIH7Centplx17hCXrGKMer3/hbYEll4fvFUa6m6QbexK3HmlXePr/uxqwGuayvnmp07lTjh6ix3LpfA6g10zy1btsosJ+IewphGySDlSqRYS2adbmzl6HWxAvsZCeHuVfrqOEj6ftHqEZ9fjkewnTVh6b4mF2jycFYKiZLCNtLH907GOX20+Men9Nh2K/Dk7fq6qecHwtYH2SXd0zbmfHDEXta7RbbGTfCJFUMVCI7v+reKzDjxKHVjEzmnJqAA1gaxGWUOH/MdsQtRwyAFvN4E1NBQZwYCk8xHGdkglQABh7fhWY7zqelVmmC6m2WtRdgOoAzTNMaptiCXI4f/G6ivLvwlEOYlu8kBjGdopSZzAwIihDxACETTKHJeWllYidJ+Ao0m1Fs57Jw74q45ZfR7zklopEZ9AO1TUM9zKj1LhC5/MtQwR9DYXCQ90hJY7ecHzhdvQ5gr2YTZNfy+ESH6UeqbsXXPQ8qfbMexaGp7xJnGbHKzheZedf8y+2hA4UVkIphwEiW0nvKo6kaD+m392QjyrwR9qyoBgHa1khONU7SQGMT8vVFxLaMnn1RLJXZbVJuZ/tbi58fc7mEi3IW4Xwo4NdwMQ1SF63RnOhBup/TcDvJxXx/mu1eUBIHT3T7CRRhnly3XxW+GImCGp1B/7gvtMnJyBrZZM626UCQ2Ooox2y62IAqmc6n6ofc9bGqE/2mJH3IwqaeXgdu7apr2PdzP/KyjW82ao/OqKmcYr4WRSteDPiHrWps9q800FfZkR1R5SrnS1XIrDYs7DoUOIsO/PypfG87bJt/b8BfbFEEXB4FAAA=

  - path: /config/ssl/ssl.key/website.key
    encoding: gzip+base64
    content: H4sIALafZFgAA22Vt66kWABEc75icjTCu/DiTWMutiEDuoF+mMa7r9+Z3XQrLZV0VCqpfv/+I1HRDOeXH4Bfnm/EIFR+WUr61/iN2IahfA9DBMCSAFQAYZ2UfA9y7UH6BkAdjDAjleauPrGUBdLGbOrlFmwzcbhhUHSIfDBFMbIWlTiSndbPHE98R9xkXCpBBrUCihOdac2cutx3fDT5B4p0F3WLOFPvgz/tDYnfYkC3l71dZmgBteTCcHiVAlWbYp/1l0Ko3/5RjTQzg66c2wCnT58iYJ7sqj9fOkBEYqe6Wu2tJHJWCQaabUplJOClRKvcrn89h4+JPeUU9/N2bb9VX4Ty0q5rifHk6n5eSB7XwhXLGca0CZrTvGwXmv0sQ2k8xaRz1gAGkDXu+6nH70A457VkX4M45+XZnTbhyUi6uNnTmDzOYiAdFzUtfSWna8lgi+S0cI2J0VAWGjKAQATfP2XLbolS0Kk4ahdx8kIwtm8WRdYeRifvDOPEUdSozOctiud0b3tiSykD1+bbxzyqkmemnFCsuVPgLFcve2pAzmIa/6DJIFNjh3XA5SXfHod9ihHBUKVQtHRwyhfzDgfByeyLfW4yq56k8tPRUaXtyGdopU1Yg+1mGfMgiJ89ygNBTGNUCUlD9I9vb4K7aU2nCQziXO9C+zJMxNxx5HPxpCB/R9P2DL8ru5CDNcTC7rIL+WluMlZw2aPYCny6b8LUa1JwpF7XbT7xXqgn4Gy/agly79u3Zw28Q1HAD/SCj3c7TVLsQ7tpC07DWu0R94NZJ6nrDGXkCi+/fV3VshJrRpcXstr2RzIVqU4VwNupeXrsMYPl8jivnDI6lI8lC3BMvm0nmAl4LEBE2y1HDU+Lb3e0EZLm/AGNzKccsVM0cZnurg2pRwPre60QS7657G6vhu8YQ2F9s+FjTz+YAJmp6m0W1RHLkDI9EmVrztfPPootU53PF3jlmw/dYRNFzd4wFLwjmuwOudNBsYM0w/8lphtUQuzRXg93u8giEuApDSR9NHryYqon2fIlG+ZDiJ/C7k6vOqE0zskhiapMTQJlXI3yuSMPHhwPQ64PmGD9ir4CCS58YFcEUGOjNCnrHNUFq3dxmjnUa2AumND5oMTFwZ/uuf4gndNKUqp+iGt9dUaQhawkh4V6P2lub7eZ+kodEOf/kEkGNdPyABHLBjghMZDkfSSnnCO40h9bBtMFFmyuNzV/mmnLnpanB0u4DD/jY5RoCs+TcCAov6SqYcwr06/bn1BElNdmm55kOdiH4/V9E72PjH7ReBOBLnJZfV/4u3rCCNcIZqVQyk3oubeWM29d8D7rGAF/Onkz3d7KwjFWU/YY32mk/92FiOluZxG7u7zMB40nY3FXx7uopqKrfHzFdA0+7ALhRRz9E9ibc56IbBYlo/+OQvl42wubNU4ZUIHpYUlaKHvSH5WWn++yHhaefRY5raM7Iv38uDsrDsznZFwhObtt+yRd8mb7anofwrXJ3MruvGsBLTGs+kowEAq8zn8d3wpyqkWs99Hp0BJrnWJQLOgwiuLdlBvta3wM8Ar4pPHFbnZcdLnreDXPBC1ylN6Y0zvnT4IhNLb5RZEGLenyRvC8CTWuPOl7MO/HyTWmTkHId6f8Uwpbyvmw65wv02ONQrgJ14uji9z+uYfaFZOx9IA6jlcvoZF6FrdGz3Fs2YIJAZOBLkx27q+zuz37OyH/XoriyP9/Nf8A5vBZx4sGAAA=

  - path: /config/cloud/custom-config.sh
    permissions: 0755
    owner: root:root
    content: |
      #!/bin/bash

      ##### Load Input Parameters #####
      . /config/cloud/onboard_config_vars

      ##### ssh_authorized_keys MODULE NOT ENABLED #####
      echo "ssh-rsa XXXXB3NzaC1yc2EAAAADAQABAAABAQClW+UyY2eWczwnEGcEtwR/ISURqmdQIpgicgVvUvZTilE5KstuyBXznpxYT3m2H/7uh5g5syAmS7rX8wSsrbtRjkFgWmDIRPaj3Dqlqqq9N+3TI3mUhMPPWuFZxhW2rK7T6OrWUw5cnJstb89OCQjH4ptqzxIV135re3nT1cJx9JZKxBeYM/tMqZHjAmCwBlj8ndbaidg/f4P0cXa3BS8etcuFGoMwnzACNtkpf6/juodedHbOW9mjamdIoOEVawHiuZNry4emxgT8x9KzBnKHAwRKhLMY/JSc+5z7n21JfDdUIa78Vv3yM3LIaZmpbBPQ7tpJpt4SmYfbhWIUm+z9 my-ssh-key" >> /home/admin/.ssh/authorized_keys

      ##### BEGIN HIGH LEVEL CONFIG ########
      curl --silent --fail --retry 20 -o /config/cloud/f5.http.v1.2.0rc4.tmpl https://raw.githubusercontent.com/f5devcentral/f5-cloud-init-examples/master/files/f5.http.v1.2.0rc4.tmpl
      curl --silent --fail --retry 20 -o /config/cloud/asm-policy-linux.tar.gz https://raw.githubusercontent.com/f5devcentral/f5-cloud-init-examples/master/files/asm-policy-linux.tar.gz
      tar xvzf /config/cloud/asm-policy-linux.tar.gz -C /config/cloud/
      tmsh create ltm node ${APP_NAME} fqdn { name ${POOL_DNS} }
      tmsh install sys crypto cert site.example.com from-local-file /config/ssl/ssl.crt/website.crt
      tmsh install sys crypto key site.example.com from-local-file /config/ssl/ssl.key/website.key
      # BEGIN CUSTOMIZE:  Policy Name/Policy URL, etc.
      # tmsh modify asm policy names below (ex. /Common/linux-${POLICY_LEVEL}) to match policy name in the xml file
      tmsh load sys application template /config/cloud/f5.http.v1.2.0rc4.tmpl
      tmsh load asm policy file /config/cloud/asm-policy-linux-${POLICY_LEVEL}.xml
      tmsh modify asm policy /Common/linux-${POLICY_LEVEL} active
      tmsh create ltm policy app-ltm-policy strategy first-match legacy
      tmsh modify ltm policy app-ltm-policy controls add { asm }
      tmsh modify ltm policy app-ltm-policy rules add { associate-asm-policy { actions replace-all-with { 0 { asm request enable policy /Common/linux-${POLICY_LEVEL} } } } }
      tmsh create sys application service ${APP_NAME} { template f5.http.v1.2.0rc4 tables add { pool__members { column-names { addr port connection_limit } rows {{ row { ${APP_NAME} ${POOL_MEMBER_PORT} 0 }}}}} variables add { asm__use_asm { value app-ltm-policy } pool__addr { value 0.0.0.0 } pool__mask { value 0.0.0.0 } pool__port { value ${VS_PORT} } pool__port_secure { value ${VS_PORT} } ssl__cert { value /Common/site.example.com.crt } ssl__key { value /Common/site.example.com.key } ssl__mode { value client_ssl } ssl_encryption_questions__advanced { value no } ssl_encryption_questions__help { value hide } monitor__http_version { value http10 } }}
      tmsh save /sys config

# Special case command required for custom use cases
# bootcmd:

# NOTE: Commands must be non blocking so long running commands (polling/waiting for mcpd) should be sent to the background
runcmd:
 - /config/cloud/onboard.sh &